-- MySQL Script generated by MySQL Workbench
-- Sat 02 Jul 2016 06:52:36 PM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema auction-website
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auction-website
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auction-website` DEFAULT CHARACTER SET utf8 ;
USE `auction-website` ;

-- -----------------------------------------------------
-- Table `auction-website`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction-website`.`user` (
  `UserID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(150) NOT NULL,
  `Firstname` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Vat` VARCHAR(45) NOT NULL,
  `HomeAddress` VARCHAR(60) NOT NULL,
  `Latitude` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  `City` VARCHAR(60) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `SignUpDate` DATE NOT NULL,
  `IsAdmin` TINYINT(1) NOT NULL DEFAULT '0',
  `isApproved` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Id_UNIQUE` (`UserID` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auction-website`.`auction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction-website`.`auction` (
  `AuctionID` BIGINT(20) NOT NULL,
  `SellerID` BIGINT(20) NOT NULL,
  `BuyerID` BIGINT(20) NULL,
  `Name` VARCHAR(150) NOT NULL,
  `Description` VARCHAR(1500) NULL DEFAULT NULL,
  `LowestBid` DOUBLE NOT NULL,
  `CurrentBid` DOUBLE NOT NULL,
  `FinalPrice` DOUBLE NOT NULL,
  `StartingDate` DATE NOT NULL,
  `EndingDate` DATE NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `NumOfBids` INT(11) NULL DEFAULT NULL,
  `Longtitude` FLOAT NULL DEFAULT NULL,
  `Latitude` FLOAT NOT NULL,
  `IsStarted` TINYINT(1) NULL DEFAULT NULL,
  `BuyPrice` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`AuctionID`),
  INDEX `fk_auction_user_idx` (`SellerID` ASC),
  INDEX `fk_auction_user1_idx` (`BuyerID` ASC),
  CONSTRAINT `fk_auction_user`
    FOREIGN KEY (`SellerID`)
    REFERENCES `auction-website`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auction_user1`
    FOREIGN KEY (`BuyerID`)
    REFERENCES `auction-website`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auction-website`.`bid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction-website`.`bid` (
  `BidderID` INT NOT NULL,
  `AuctionID` INT NOT NULL,
  `BidTime` DATE NOT NULL,
  `Amount` INT NOT NULL,
  INDEX `fk_bid_auction1_idx` (`AuctionID` ASC),
  INDEX `fk_bid_user1_idx` (`BidderID` ASC),
  PRIMARY KEY (`BidderID`, `AuctionID`),
  CONSTRAINT `fk_bid_auction1`
    FOREIGN KEY (`AuctionID`)
    REFERENCES `auction-website`.`auction` (`AuctionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bid_user1`
    FOREIGN KEY (`BidderID`)
    REFERENCES `auction-website`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auction-website`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction-website`.`category` (
  `CategoryID` INT(11) NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auction-website`.`auctionCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction-website`.`auctionCategory` (
  `AuctionId` INT(11) NOT NULL,
  `CategroryId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`AuctionId`),
  INDEX `fk_auctionCategory_category1_idx` (`CategroryId` ASC),
  CONSTRAINT `fk_auctionCategory_category1`
    FOREIGN KEY (`CategroryId`)
    REFERENCES `auction-website`.`category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auctionCategory_auction1`
    FOREIGN KEY (`AuctionId`)
    REFERENCES `auction-website`.`auction` (`AuctionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auction-website`.`itemImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction-website`.`itemImage` (
  `AuctionId` BIGINT(20) NOT NULL,
  `ImageFileName` VARCHAR(100) NOT NULL DEFAULT NULL,
  PRIMARY KEY (`ImageFileName`),
  CONSTRAINT `fk_itemImage_auction1`
    FOREIGN KEY (`AuctionId`)
    REFERENCES `auction-website`.`auction` (`AuctionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auction-website`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction-website`.`messages` (
  `MessageID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `SenderID` INT(11) NOT NULL,
  `ReceiverID` INT(11) NOT NULL,
  `Message` VARCHAR(1000) NOT NULL,
  `ReceivedDate` DATE NOT NULL,
  `IsRead` TINYINT(1) NOT NULL DEFAULT '0',
  `AuctionID` INT(11) NOT NULL,
  PRIMARY KEY (`MessageID`),
  INDEX `fk_messages_user1_idx` (`SenderID` ASC),
  INDEX `fk_messages_user2_idx` (`ReceiverID` ASC),
  UNIQUE INDEX `MessageID_UNIQUE` (`MessageID` ASC),
  INDEX `fk_messages_auction1_idx` (`AuctionID` ASC),
  CONSTRAINT `fk_messages_user1`
    FOREIGN KEY (`SenderID`)
    REFERENCES `auction-website`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_user2`
    FOREIGN KEY (`ReceiverID`)
    REFERENCES `auction-website`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_auction1`
    FOREIGN KEY (`AuctionID`)
    REFERENCES `auction-website`.`auction` (`AuctionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `auction-website`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction-website`.`rating` (
  `FromID` BIGINT(20) NOT NULL DEFAULT NULL,
  `ToID` BIGINT(20) NOT NULL DEFAULT NULL,
  `Rate` INT NOT NULL,
  INDEX `fk_rating_user1_idx` (`FromID` ASC),
  INDEX `fk_rating_user2_idx` (`ToID` ASC),
  PRIMARY KEY (`FromID`, `ToID`),
  CONSTRAINT `fk_rating_user1`
    FOREIGN KEY (`FromID`)
    REFERENCES `auction-website`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_user2`
    FOREIGN KEY (`ToID`)
    REFERENCES `auction-website`.`user` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
