-- MySQL Script generated by MySQL Workbench
-- Sun 17 Apr 2016 03:18:27 PM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Auction-Website
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Auction-Website
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Auction-Website` DEFAULT CHARACTER SET utf8 ;
USE `Auction-Website` ;

-- -----------------------------------------------------
-- Table `Auction-Website`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Auction-Website`.`User` (
  `UserID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(150) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `AFM` VARCHAR(45) NOT NULL,
  `HomeAddress` VARCHAR(60) NOT NULL,
  `City` VARCHAR(60) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `SignUpDate` DATE NOT NULL,
  `IsAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  `isApproved` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Id_UNIQUE` (`UserID` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `AFM_UNIQUE` (`AFM` ASC),
  UNIQUE INDEX `e-mail_UNIQUE` (`e-mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Auction-Website`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Auction-Website`.`Transaction` (
  `TransactionID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `SellerID` BIGINT(20) NOT NULL,
  `BuyerID` BIGINT(20) NOT NULL,
  `ItemName` VARCHAR(150) NOT NULL,
  `ItemPrice` DOUBLE NOT NULL,
  PRIMARY KEY (`TransactionID`),
  UNIQUE INDEX `TransactionID_UNIQUE` (`TransactionID` ASC),
  INDEX `fk_Transaction_2_idx` (`SellerID` ASC),
  UNIQUE INDEX `SellerID_UNIQUE` (`SellerID` ASC),
  UNIQUE INDEX `BuyerID_UNIQUE` (`BuyerID` ASC),
  CONSTRAINT `fk_Transaction_1`
    FOREIGN KEY (`BuyerID`)
    REFERENCES `Auction-Website`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_2`
    FOREIGN KEY (`SellerID`)
    REFERENCES `Auction-Website`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Auction-Website`.`SellerInbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Auction-Website`.`SellerInbox` (
  `MessageID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ConversationID` BIGINT(20) NOT NULL,
  `Message` VARCHAR(1000) NOT NULL,
  `SendDate` DATE NOT NULL,
  `isRead` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`MessageID`),
  INDEX `fk_SellerInbox_1_idx` (`ConversationID` ASC),
  UNIQUE INDEX `MessageId_UNIQUE` (`MessageID` ASC),
  UNIQUE INDEX `ConversationID_UNIQUE` (`ConversationID` ASC),
  CONSTRAINT `fk_SellerInbox_1`
    FOREIGN KEY (`ConversationID`)
    REFERENCES `Auction-Website`.`Transaction` (`TransactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Auction-Website`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Auction-Website`.`Items` (
  `ItemID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(150) NOT NULL,
  `Description` VARCHAR(100) NULL,
  `StartingPrice` DOUBLE NOT NULL,
  `CurrentBid` DOUBLE NOT NULL,
  `FinalPrice` DOUBLE NOT NULL,
  `StartingDate` DATE NOT NULL,
  `EndingDate` DATE NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `UserID (Seller)` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ItemID`),
  INDEX `fk_Items_1_idx` (`UserID (Seller)` ASC),
  UNIQUE INDEX `ItemId_UNIQUE` (`ItemID` ASC),
  CONSTRAINT `fk_Items_1`
    FOREIGN KEY (`UserID (Seller)`)
    REFERENCES `Auction-Website`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Auction-Website`.`UserInbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Auction-Website`.`UserInbox` (
  `MessageID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ConversationID` BIGINT(20) NOT NULL,
  `Message` VARCHAR(1000) NOT NULL,
  `ReceivedDate` DATE NOT NULL,
  `isRead` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`MessageID`),
  INDEX `fk_UserInbox_1_idx` (`ConversationID` ASC),
  UNIQUE INDEX `MessageID_UNIQUE` (`MessageID` ASC),
  UNIQUE INDEX `ConversationID_UNIQUE` (`ConversationID` ASC),
  CONSTRAINT `fk_UserInbox_1`
    FOREIGN KEY (`ConversationID`)
    REFERENCES `Auction-Website`.`Transaction` (`TransactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
